#Câu 9: Giải thích kết quả tính toán của các biểu thức
import math
i1 = 2; i2 = 5; i3 = -3
d1 = 2.0; d2 = 5.0; d3 = -0.5

# Câu (a)
kq1 = i1 + (i2 * i3); print("Ket qua cau A la:", kq1)
# Câu (b)
kq2 = i1 * (i2 + i3); print("Ket qua cau B la:", kq2)
# Câu (c)
kq3 = i1 / (i2 + i3); print("Ket qua cau C la:", kq3)
# Câu (d)
kq4 = i1 // (i2 + i3); print("Ket qua cau D la:", kq4)
# Câu (e)
kq5 = i1 / i2 + i3; print("Ket qua cau E la:", kq5)
# Câu (f)
kq6 = i1 // i2 + i3; print("Ket qua cau F la:", kq6)
# Câu (g)
kq7 = 3 + 4 + 5 / 3; print("Ket qua cau G la:", kq7)
# Câu (h)
kq8 = 3 + 4 + 5 // 3; print("Ket qua cau H la:", kq8)
# Câu (i)
kq9 = (3 + 4 + 5) / 3; print("Ket qua cau I la:", kq9)
# Câu (j)
kq10 = (3 + 4 + 5) // 3; print("Ket qua cau J la:", kq10)
# Câu (k)
kqA = d1 + (d2 * d3); print("Ket qua cau K la:", kqA)
# Câu (l)
kqB = d1 + d2 * d3; print("Ket qua cau L la:", kqB)
# Câu (m)
kqC = d1 / d2 - d3; print("Ket qua cau M la:", kqC)
# Câu (n)
kqD = d1 / (d2 - d3); print("Ket qua cau N la:", kqD)
# Câu (o)
kqE = d1 + d2 + d3 / 3; print("Ket qua cau O la:", kqE)
# Câu (p)
kqF = (d1 + d2 + d3) / 3; print("Ket qua cau P la:", kqF)
# Câu (q)
kqG = d1 + d2 + (d3 / 3); print("Ket qua cau Q la:", kqG)
# Câu (r)
kqH = 3 * (d1 + d2) * (d1 - d3); print("Ket qua cau R la:", kqH)