print("==")
s = input("Nhap chuoi: ")
upper = sum(1 for c in s if c.isupper())
lower = sum(1 for c in s if c.islower())
digits = sum(1 for c in s if c.isdigit())
spaces = sum(1 for c in s if c.isspace())
special = len(s) - (upper + lower + digits + spaces)
vowels = sum(1 for c in s.lower() if c in "aeiou")
consonants = sum(1 for c in s.lower() if c.isalpha() and c not in "aeiou")

print("So chu in hoa:", upper)
print("So chu thuong:", lower)
print("So chu so:", digits)
print("So khoang trang:", spaces)
print("So ky tu dac biet:", special)
print("So nguyen am:", vowels)
print("So phu am:", consonants)
